# Generated by Django 4.2.3 on 2023-08-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0019_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='starred_articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
